### PR TITLE
Add support for thread safety on async actions only

### PR DESCRIPTION
**Pull request by srajko**
Adds a middle-ground thread-safety level, which locks async functions but skips locking of sync functions, to avoid the risk of blocking the main thread.

/cc @johnhaley81 @joshaber

### CODE REVIEW

**Comment by srajko** [comment]
It's backwards compatible with `NodeGit.enableThreadSafety()` but looks like I took away `NodeGit.disableThreadSafety()` (you would have to use the more general `NodeGit.setThreadSafetyStatus`).

**Comment by srajko** [comment]
BTW the async-only thread-safety is activated using `NodeGit.setThreadSafetyStatus(1)`.  `NodeGit.enableThreadSafety()` still does the full async+sync locking (equivalent to `NodeGit.setThreadSafetyStatus(2)`)

**Comment by joshaber** [comment]
Thanks @srajko!

**Comment by johnhaley81** [comment]
> It might be nice to add more user-friendly identifiers instead of 1 and 2 (and 0 - disabled)

Let's make those strings that live on `NodeGit.THREAD_SAFETY` to be a little more clear.

**Comment by srajko** [comment]
> Let's make those strings that live on NodeGit.THREAD_SAFETY to be a little more clear.

:+1: added.

**Comment by johnhaley81** [comment]
@srajko thanks!

**Pull request merged**
