### PR TITLE
Mark the output param of treebuilder.write. Its unusable otherwise be…

### PR DESCRIPTION
**Pull request by tannewt**
…cause one cannot instantiate an Oid to pass in.

### CODE REVIEW

**Comment by tbranyen** [comment]
Awesome thanks, is this something you'd feel comfortable writing a unit test for?

**Comment by tannewt** [comment]
I can. Do have an example I can base it off of?

**Comment by tbranyen** [comment]
Doesn't look like we have a treebuilder file yet, create one and base off of:

https://github.com/nodegit/nodegit/blob/master/test/tests/tree_entry.js

**Comment by tbranyen** [comment]
Would rather have this in than out.  We can revisit a test later.

**Pull request merged**
