### PR TITLE
Turn extended testing back on

### PR DESCRIPTION
**Pull request by stevex86**

### CODE REVIEW

**Comment by Croydon** [comment]
This is issue #1449

**Comment by implausible** [comment]
Testing from smart git

**Comment by stevex86** [comment]
Looks like this repo has migrated to GitHub actions. That's awesome! In the interest of keeping this PR from going completely stale, what can we do to get it moving again?

**Comment by implausible** [comment]
My apologies for the reach out. I've been poking at some github APIs. I should've been testing against a private PR.

As far as getting this PR moving again. I dug into extended testing a bit, and it looks like the mechanism for extended testing no longer exists in node-gyp. I don't believe we will be turning extended testing back on without a new plan.

**Pull request closed without merging**
