### PR TITLE
Add missing 'promise' dependency

### PR DESCRIPTION
**Pull request by lowellk**

### CODE REVIEW

**Comment by johnhaley81** [comment]
All of the versions of node that we target have `Promise` natively. Where is this breaking for you?

**Comment by lowellk** [comment]
@johnhaley81 I'm running node 0.10. Is that not supported?

**Comment by johnhaley81** [comment]
Unfortunately no. We decided to stop support for node v0.10 when 5 was released. Are you able to use NodeGit in v0.10 with this patch?

**Comment by lowellk** [comment]
My system was running 0.10 but I realize the best solution for me is to simply upgrade my version. Thanks for responding.

**Pull request closed without merging**
