### PR TITLE
Define GIT_SSH_MEMORY_CREDENTIALS for libgit2

### LINKED ISSUE #760: Prebuilt binary libgit2 not built with GIT_SSH_MEMORY_CREDENTIALS defined
Hi! When I call Cred.sshKeyMemoryNew, I get this error message:

```
Error: This version of libgit2 was not built with ssh memory credentials.
    at Error (native)
```

"npm install" installed prebuilt binaries for nodegit.

I'm running Node 4.0.0 on x86_64 Linux. THis is nodegit 0.5.0.

I believe this means libgit2 [should be built with GIT_SSH_MEMORY_CREDENTIALS defined](https://github.com/libgit2/libgit2/blob/master/src/transports/cred.c#L203).

I'm filing this after talking to @johnhaley81 in gitter.

### PR DESCRIPTION
**Pull request by alantrrs**
Compile libgit2 with GIT_SSH_MEMORY_CREDENTIALS defined to allow
sshKeyMemoryNew to work.

Fixes #760

### CODE REVIEW

**Comment by alantrrs** [comment]
This is just a rebase of #763 . However it seems like tests are still failing.

**Comment by alantrrs** [comment]
Rebased again. However it looks like the version of libssh2 used here is not updated since it doesn't include ``libssh2_userauth_publickey_frommemory``.

Any plans to update it?

**Comment by johnhaley81** [comment]
We could update libssh2 in a different PR.

**Comment by richardkazuomiller** [comment]
Is there any status update on this and/or updating libssh2? I'd like to use `sshKeyMemoryNew`. I'm not good enough at C to figure out how to contribute at all though, sorry (^^ゞ

**Comment by jamon** [comment]
This definitely works with libssh2.  I'm happy to walk through the steps to get it working, below, but I'm not familiar enough with node-gyp and nodegit's build process to do it in a pull-request worthy way.

checkout the latest nodegit code and do the following (only tested on linux):

- remove vendor/libssh2 entirely and commit this
- cd vendor ; git clone -b tags/libssh2-1.7.0 https://github.com/libssh2/libssh2.git (this could be done as a submodule if you'd like)
- cd libssh2 ; ./buildconf
- cd ../.. ; npm install
- sudo npm link -g
- add "GIT_SSH_MEMORY_CREDENTIALS" to the "defines" array for libgit2 (part of this pull request shows this part)

use the globally installed nodegit from your projects

**Comment by maxkorp** [comment]
@jamon which OS were you testing on though? I've got a pr here: https://github.com/nodegit/nodegit/pull/1071

But it dies for windows

**Comment by maxkorp** [comment]
Up to date! @alantrrs care to rebase on top of master?

**Comment by alantrrs** [comment]
rebased

**Comment by maxkorp** [comment]
Nice, TY

**Comment by kid** [comment]
Any changes to see this in a new release soon?
I'm trying to install from master but I'm facing other issues

Thanks!

**Pull request merged**
