### PR TITLE
Added debug build instructions.

### PR DESCRIPTION
**Pull request by mcollina**
As discussed in #331.

### CODE REVIEW

**Comment by tbranyen** [comment]
Thanks!

**Comment by johnhaley81** [comment]
Gracias amigo! :D

**Comment by maxkorp** [comment]
One concern from my corner: I'm hoping to push a pretty large restructure of the build process this afternoon, which will invalidate these particular instructions (down to a simple "npm run build-debug" or such).

**Comment by maxkorp** [comment]
Eh, that requires some bigger discussion before it can land. I'm merging this, no way did your readme change cause appveyor to fail.

**Comment by mcollina** [comment]
appveyor fails almost every time :(, what's is purpose once we get travis?

**Comment by johnhaley81** [comment]
It's the only real CI we have for windows. I can't figure out why it dies
though.

**Pull request merged**
