### PR TITLE
Plaintext credential not async

### PR DESCRIPTION
**Pull request by mbleigh**
I have no idea what I'm doing, but @johnhaley81 told me this would fix a segfault in Gitter :wink:

### CODE REVIEW

**Comment by johnhaley81** [comment]
@maxkorp updated the tests as well, can you rebase this branch on top of https://github.com/nodegit/nodegit/tree/cred-fixes please?

**Comment by johnhaley81** [comment]
oh, hah apparently he implemented the change as well.

**Comment by mbleigh** [comment]
Well, looks like this is being taken care of without me.

**Comment by maxkorp** [comment]
Whooooops. Sorry, I didn't see that you had already done this.

**Pull request closed without merging**
