### PR TITLE
Status.byIndex and StatusEntry

### PR DESCRIPTION
**Pull request by orderedlist**
Getting this started, but something weird is going on with the deltas.

```
1) StatusList gets status with deltas:
     AssertionError: "���\u000f\u0013\u0017" == "my-new-file-that-shouldnt-exist.file"
      at /Users/steve/github/nodegit/test/tests/status_list.js:46:18
      at /Users/steve/github/nodegit/node_modules/nodegit-promise/lib/core.js:64:15
      at flush (/Users/steve/github/nodegit/node_modules/nodegit-promise/node_modules/asap/asap.js:27:13)
      at process._tickCallback (node.js:419:13)
```

### CODE REVIEW

**Comment by orderedlist** [comment]
Ok, I'm happy with this current implementation. StatusEntries get more context than the statuses we get from Status.forEach. With the latter, we only get a status bit and a path. With the StatusEntry we get not only the status bit, but the deltas from head-to-index and index-to-workdir, including old and new file info. This makes identifying renames possible, along with lots of other stuff.

I was thinking we might want to add a convenience method like `Repository.getExtendedStatuses` to grab this info. Does that sound good?

**Comment by johnhaley81** [comment]
Sound great, do it up.

**Comment by orderedlist** [comment]
Convenience method added as `Repository.getStatusExt`. I'll wait for a plus-one before merging.

**Comment by johnhaley81** [comment]
:+1:

**Pull request merged**
