### PR TITLE
build: use pkg-config to find curl header

### PR DESCRIPTION
**Pull request by rsmarples**
pkgsrc (as used by NetBSD) installs package headers in non default
locations.
The solution is to use pkg-config to work out the correct location
via CFLAGS.

### CODE REVIEW

**Comment by tbranyen** [comment]
Looks good to me :+1:

**Comment by rsmarples** [comment]
no idea what happened here, I'll redo

**Comment by myfreeweb** [comment]
The `"<!(pkg-config libcurl --cflags 2>/dev/null || echo)"` line is also required on FreeBSD.

**Comment by rsmarples** [comment]
See PR #1237 for a better solution. Bump that one instead ;)

**Pull request closed without merging**
