### PR TITLE
Added diff functions with options parameter.

### PR DESCRIPTION
**Pull request by ayresa**
Allows options for diffs so that we can do things like exclude whitespace for example.

### CODE REVIEW

**Comment by johnhaley81** [comment]
@tbranyen do you know why coverage is dying on linux?

**Comment by tbranyen** [comment]
Nope, I'll wait till the rebuild happens and check.

**Comment by tbranyen** [comment]
Looks fine :-p

**Comment by johnhaley81** [comment]
Nothing to see here :)

**Pull request merged**
