### PR TITLE
Put the path to node-pre-gyp in quotes in install.js

### PR DESCRIPTION
**Pull request by Gum-Joe**
Hi,
When I was installing nodegit, I found that there was compilation issues (#950). On further inspection, I found out that the building was taking place due to it failing to install a S3 binary. This was due to my user folder having a space in.

To fix this, I have placed the command in quotes.

**Current Issues:**

- `install.js` now assumes that the install is a local install, even though that part of code was untouched.

### CODE REVIEW

**Comment by Gum-Joe** [comment]
The linting script appears to be failing (appveyor build)

**Comment by johnhaley81** [comment]
Do `"\""` instead of `'"'`

**Comment by Gum-Joe** [comment]
Ok

**Comment by Gum-Joe** [comment]
Test status:
It appears to be one test is failing. As I did not touch the tests, I believe this is because of how the tests have been written, or an incomplete/buggy test. Please correct me if I am wrong.

**Comment by tbranyen** [comment]
@Gum-Joe you are correct, my server is down which is causing the failure.

**Comment by johnhaley81** [comment]
@Gum-Joe can you rebase this on top of master please?

**Comment by Gum-Joe** [comment]
:@johnhaley81 Rebasing now

**Comment by Gum-Joe** [comment]
Just rebased. Now pull requests will not merge

**Comment by johnhaley81** [comment]
Yeah, it pulled in too many commits. You just need https://github.com/nodegit/nodegit/pull/951/commits/612540e02965503f3e91aced8c567374a12fcd3a and  https://github.com/nodegit/nodegit/pull/951/commits/f451b689fe9f3a74e072178a2187d675424ea1df

**Comment by Gum-Joe** [comment]
How can I fix this?

**Comment by Gum-Joe** [comment]
Oh... Now GitHub says it can merge.

**Comment by tbranyen** [comment]
It might be better to just merge locally @johnhaley

**Comment by johnhaley81** [comment]
[Merged manually](https://github.com/nodegit/nodegit/commit/9789e017b9318ba5a48699c83a394f53e061eb6a)

**Comment by johnhaley81** [comment]
Thanks @Gum-Joe!

**Comment by Gum-Joe** [comment]
Your welcome @johnhaley81

**Pull request closed without merging**
