### PR TITLE
Check for existence to avoid throwing an error when there is no default signature

### PR DESCRIPTION
**Pull request by tomruggs**

### CODE REVIEW

**Comment by tbranyen** [comment]
Looks good, think you could write us a test as well? If you need help hop in the Gitter channel and we'll help ya with it :D

**Comment by tomruggs** [comment]
The existing test has been fixed to fail on error.  I verified that the test failed without my fix and passes with it.

**Comment by johnhaley81** [comment]
Thanks for the PR!

**Comment by tomruggs** [comment]
Np.  Thanks for the merge.

**Pull request merged**
