### PR TITLE
Wrap toolPath in quotes instead of escaping spaces

### LINKED ISSUE #850: Install fails on Windows with space in directory name
>[nodegit] Everything is ready to go, attempting compilation
> { [Error: Command failed: `C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\...\Open\ Source\...\node_modules\nodegit\node_modules\.bin\node-gyp rebuild"`
`'C:\Users\...\Open\'` is not recognized as an internal or external command,
operable program or batch file.
]

Windows does not allow `\` to escape spaces.  

There are two solutions:

 1. Remove the `\`s as well as the `/s` flag.  `cmd` will then treat the quotes as part of the command to execute
 2. Remove the `\`s, but keep the `/s` flag.  Then, wrap both the entire command and the pass to `node-gyp` in quotes:  
`cmd /s /c "".../node-gyp" rebuild"`

### PR DESCRIPTION
**Pull request by SLaks**
For better Windows support.
Fixes #850

### CODE REVIEW

**Comment by SLaks** [comment]
Bash also supports this syntax (running a command from a quoted string)

**Comment by johnhaley81** [comment]
AppVeyor died due to a timeout issue. I restarted.

**Comment by SLaks** [comment]
It looks like Travis also timed out.
https://travis-ci.org/nodegit/nodegit/jobs/100367183

You might want to increase that test's timeout.

**Comment by johnhaley81** [comment]
This looks great. I'll merge after CI passes. Thanks @SLaks!

**Pull request merged**
