### PR TITLE
Update supported Node JS versions

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Adds io.js 3 to the Travis CI environment test matrix

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
[Errors thrown](https://travis-ci.org/nodegit/nodegit/jobs/75297165#L752) appear to be related to the [V8 update in io.js 3](https://github.com/nodejs/node/wiki/Breaking-Changes#v8-upgrade)

**Comment by johnhaley81** [comment]
I think this will require a bump to the latest [nan](https://github.com/nodejs/nan/releases/tag/v2.0.5)

**Comment by ChristianMurphy** [comment]
bumping nan to 2.0.5 allows support for io.js 3, but currently appears to break many of the openssl and  libgit2 bindings. :frowning:

**Comment by tbranyen** [comment]
I've said it before, and unfortunately again.  io.js is a great moving target, but a nightmare to support with native code.  We'll continuously support Node, but we'll need an io.js advocate who will maintain parity if we want to support latest.  I don't think it's fair to ask our devs who have little time as-is to support something that breaks as often.

**Comment by ChristianMurphy** [comment]
@tbranyen fair enough.
I removed the io.js 3 tests, updated engines to give a warning if version 3+ is used and added a note in the `README` on support.
Would it be safe to say that [Node JS Long Term Support](https://github.com/nodejs/LTS) releases will be supported by NodeGit?

**Comment by tbranyen** [comment]
@ChristianMurphy "It should be stated that the abstraction layer (currently NAN) should support all current LTS releases. " If that can hold true, then absolutely!

**Comment by tbranyen** [comment]
@ChristianMurphy according to this: https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d it's in our best interest to support iojs v3

**Comment by ChristianMurphy** [comment]
Cool, would you like me to re-add the `io.js 3` tests? (probably as allow failure for now)

**Comment by tbranyen** [comment]
@ChristianMurphy so it's only failing in Windows then? surprising

**Comment by tbranyen** [comment]
Oh derp, allowed failure

**Comment by ChristianMurphy** [comment]
Yep, and the build failure on Windows appears to be AppVeyor flaking out rather than an actual build failure.
Thoughts on the changes made in the PR? :thought_balloon:

**Comment by tbranyen** [comment]
@ChristianMurphy can you bump us to nan 2.0 in here too?

**Comment by ChristianMurphy** [comment]
@tbranyen updated :+1:

**Comment by johnhaley81** [comment]
Well that broke everything :)

**Comment by tbranyen** [comment]
Merge it!

**Comment by dukex** [comment]
Why not use 'node_js' config? 
http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against

**Comment by ChristianMurphy** [comment]
OS X build currently do not support the `node_js` config.

Ref https://github.com/travis-ci/travis-ci/issues/2311

**Comment by dukex** [comment]
:/  my  bad, thank you @ChristianMurphy

**Comment by ChristianMurphy** [comment]
@dukex no worries :smile: 
It threw me for a loop when I tried it in e929f76 and everything blew up :frowning: 
Hopefully Travis will eventually add Node JS for OS X to their [roadmap](http://next.travis-ci.com/)

**Comment by johnhaley81** [comment]
Trying to get nan v2 working in #702

**Pull request closed without merging**
