### PR TITLE
Move postinstall script from bash to node

### PR DESCRIPTION
**Pull request by johnhaley81**

### CODE REVIEW

**Comment by johnhaley81** [comment]
@martinheidegger could you confirm that this still works for you? I don't have a linux box handy.

**Comment by johnhaley81** [comment]
Confirmed that it worked in a VM that I have.

**Comment by martinheidegger** [comment]
Awesome, sorry for being late

**Comment by tbranyen** [comment]
No worries, Microsoft has been late since the 80s: http://venturebeat.com/2016/03/30/microsoft-is-bringing-the-bash-shell-to-windows/

**Comment by johnhaley81** [comment]
@martinheidegger you were just ahead of your time.

**Pull request merged**
