### PR TITLE
Make Tree#createUpdated usable

### PR DESCRIPTION
**Pull request by rafaelgieschke**
Currently, `Tree#createUpdated` is not usable as new `TreeUpdate`s cannot be constructed and `createUpdated(repo, nupdates, updates)` only accepts a single `TreeUpdate` as `updates`.

This pull request allows to `new TreeUpdate()` and turns `updates` into an `Array<TreeUpdate>`.

Usage is, e.g., as follows:

```javascript
#!/usr/bin/env node

const Git = require("nodegit");

(async () => {
  const repo = await Git.Repository.init("test", 1);
  const odb = await repo.odb();
  const emptyTree = await repo.getTree(await odb.write("", 0, Git.Object.TYPE.TREE));
  const oid = await odb.write("test\n", 5, Git.Object.TYPE.BLOB);

  const update = new Git.TreeUpdate();
  update.action = Git.Tree.UPDATE.UPSERT;
  update.filemode = Git.TreeEntry.FILEMODE.BLOB;
  update.id = oid;
  update.path = "directory1/file";

  const update2 = new Git.TreeUpdate();
  update2.action = Git.Tree.UPDATE.UPSERT;
  update2.filemode = Git.TreeEntry.FILEMODE.BLOB;
  update2.id = oid;
  update2.path = "directory2/file";

  const treeOid = await emptyTree.createUpdated(repo, 2, [update, update2]);
  console.log(treeOid);
})();
```

### CODE REVIEW

**Comment by johnhaley81** [comment]
@rafaelgieschke sorry about taking so long to look at this. This is great! Could you provide some tests to ensure functionality now and in the future please?

**Comment by johnhaley81** [comment]
Perfect, thanks!

**Comment by rafaelgieschke** [comment]
@johnhaley81 Thanks for looking at this. I added a simple test.

**Comment by stewartlord** [comment]
Hey @rafaelgieschke and @johnhaley81. I was curious if this change is ready to be merged? It looks like it might have been forgotten.

**Comment by rafaelgieschke** [comment]
@stewartlord Yes, this and #1255 should be ready to be merged.

**Comment by JoostK** [comment]
This would be great! Any chance it can be rebased and get merged?

**Pull request merged**
