### PR TITLE
revwalk: Add missing "async" annotations to getCommits() methods

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by johnhaley81** [comment]
Thanks for the doc update!

**Comment by Turbo87** [comment]
Will this automatically update the website repo too?

**Comment by tbranyen** [comment]
@Turbo87 not yet, if you go to https://github.com/nodegit/nodegit.github.com you can regen the site and open a pr with the changes

**Comment by Turbo87** [comment]
@tbranyen I guess it should be rather straight forward to get TravisCI to do website updates. Let me know if you need someone to work on that.

**Comment by tbranyen** [comment]
@Turbo87 yes please!

**Comment by johnhaley81** [comment]
@Turbo87 omg plz yes :+1:

**Comment by tbranyen** [comment]
@Turbo87 if you have any questions about it, please join our gitter channel, we'd be happy to help you through any blockers

**Pull request merged**
