### PR TITLE
build against shared library for libcurl

### PR DESCRIPTION
**Pull request by implausible**
To get proxy support into NodeGit, we will need to get libgit configured to use libcurl. To start, we will just try to build nodegit against libcurl using the -lcurl flag.

We will also expose and handle proxy_options, the goal of this PR is to get proxy support in full across all systems.

This should address https://github.com/nodegit/nodegit/issues/489

### CODE REVIEW

**Comment by implausible** [comment]
Testing this is proving to be quite difficult. Issues are that we want to assert that we (@cbargren in da house) are going over a proxy. We need to figure out a way to create a proxy on the fly on our test boxes that we can tell nodegit to use that also can be checked at the end of the test if it was hit or not... we've looked through several libraries today and so far nothing is working for us :(

**Comment by implausible** [comment]
Getting proxy options fully tested is going to be _very_ difficult. For now, this passes all of the test cases, and does not worsen NodeGit. Had a discussion with @johnhaley81, we'll come back for tests on this when we have a good framework for an on-the-fly forward proxy.

**Comment by maxkorp** [comment]
Probably a custom proxy through express or something would be easiest.

**Comment by maxkorp** [comment]
Looking at this now.

**Comment by johnhaley81** [comment]
Tested this in a proxied environment and confirmed it worked. Thanks @implausible.

**Comment by saper** [comment]
this breaks my FreeBSD build since it cannot find `<curl/curl.h>` (It is in `/usr/local/include/curl/curl.h`).

This change should use `curl-config` to figure out compiler and linking options to get it working.

**Pull request merged**
