### PR TITLE
WIP: Fix test issues

### PR DESCRIPTION
**Pull request by maxkorp**
There were some slashes getting through to exec in the test runner which I suspect is behind #316. 
This fixes those, and a few other things.

### CODE REVIEW

**Comment by johnhaley81** [comment]
Nope :(

Any other ideas?

**Comment by johnhaley81** [comment]
Are we good to merge this in?

**Comment by maxkorp** [comment]
Not quite, tidying up some messes i made first, and I want to rebase etc beforehand. Gimme 30 to an hour :+1:

**Comment by johnhaley81** [comment]
Great job on this btw. I hope this clears up our windows test issues :)

**Comment by maxkorp** [comment]
I'm hoping so. I was able to repro both issues in windows (clone not quite as consistantly, but fairly regularly) and they're both working locally now (and still work in osx), so I'm hopeful.

The big takeaway here is to listen to node-gyp's warnings about uninitialized vars, that's what was biting us with the status tests. 

What weirds me out is that the status tests were passing for me locally before...

**Comment by maxkorp** [comment]
Huzzah!

**Pull request merged**
