### PR TITLE
escape the spaces in dir for shell command

### PR DESCRIPTION
**Pull request by iloahz**
This should fix the issue in https://github.com/nodegit/nodegit/issues/1082

### CODE REVIEW

**Comment by jacobmarshall** [comment]
I'm hoping this can be merged in soon. Sadly I need this for my build system to work correctly.

**Comment by johnhaley81** [comment]
Thanks @iloahz.

Sorry that NodeGit didn't work for you @jacobmarshall. It is pretty big so I can understand it not fitting into your use case.

**Comment by jacobmarshall** [comment]
> Sorry that NodeGit didn't work for you @jacobmarshall. It is pretty big so I can understand it not fitting into your use case.

Thanks @johnhaley81, I seriously appreciate your work. `nodegit` is a beautifully eloquent library. I look forward to using it in the future.

**Comment by johnhaley81** [comment]
image

**Pull request merged**
