### PR TITLE
Adds support for strarray in structs

### PR DESCRIPTION
**Pull request by orderedlist**
Pathspecs happen a ton in options structs, we can finally checkout individual 
files, etc.

I'll want some :eyes: on this to make sure the C++ isn't doing anything wrong or leaking somewhere.

### CODE REVIEW

**Comment by mattyclarkson** [comment]
Results in:

```c++
NAN_SETTER(GitCheckoutOptions::SetPaths)
{
  NanScope();

  GitCheckoutOptions *wrapper = ObjectWrap::Unwrap<GitCheckoutOptions>(args.This());

  Handle<Object> paths(value->ToObject());
  NanDisposePersistent(wrapper->paths);

  NanAssignPersistent(wrapper->paths, paths);

  wrapper->raw->paths = * StrArrayConverter::Convert(paths->ToObject()) ;

}
```

**Comment by johnhaley81** [comment]
That generated C++ looks good.

**Comment by johnhaley81** [comment]
I'd say lets add in a test to confirm this works and then merge it in.

**Comment by orderedlist** [comment]
Ok, test is in place. Someone sanity-check that please, and we can merge.

**Comment by tbranyen** [comment]
This looks good to me!

**Comment by mattyclarkson** [comment]
@orderedlist, looks good. builds fine here.

**Comment by orderedlist** [comment]
yes

**Comment by johnhaley81** [comment]
:+1: to that gif

**Pull request merged**
