### PR TITLE
make checkoutBranch works with branches that lives outside of refs/heads

### PR DESCRIPTION
**Pull request by AsoSunag**
And avoid trying to call a method on a boolean when isBranch() is false.

### CODE REVIEW

**Comment by johnhaley81** [comment]
So I could be wrong but I'm pretty sure that anything that exists outside of `refs/heads` is, according to git, *not* a branch. So this function is doing what it is supposed to be doing. I definitely see the use case for this though.

Let's abstract this out to `checkoutRef` and then make another method that's called `checkoutBranch` that has the old functionality. Maybe have `checkoutBranch` confirm that the ref is indeed a branch before calling `checkoutRef` and then rejecting if it isn't.

**Comment by AsoSunag** [comment]
Hello,

Yes you're right, I did that for remotes. It is good idea to have a checkoutRef and a checkoutBranch. The only thing that is bothering me with that is that when using checkoutRef with a non branch reference we will still use getBranchCommit. So we could keep one method checkoutBranch checking if it is a branch or a remote or we can have two methods.

What do you think is the best?

**Comment by johnhaley81** [comment]
`Repository#getBranchCommit` just calls `Repository#getReferenceCommit` so we can replace that call with `Repository#getReferenceCommit`

**Comment by AsoSunag** [comment]
ah ok I'll do that then.

**Comment by johnhaley81** [comment]
LGTM Thanks @AsoSunag

**Pull request merged**
