### PR TITLE
Bump nan to v2

### PR DESCRIPTION
**Pull request by johnhaley81**

### CODE REVIEW

**Comment by ssreekanth** [comment]
:+1:

**Comment by tbranyen** [comment]
https://github.com/nodejs/node/issues/2798

**Comment by saper** [comment]
I think there's nothing node-specific in those failure - it's just a different warning level enforced by the compiler (using clang on FreeBSD here):

````../vendor/libgit2/src/attr.c:10:1: warning: unused function 'kh_clear_str' [-Wunused-function]
GIT__USE_STRMAP
^
../vendor/libgit2/src/strmap.h:24:2: note: expanded from macro 'GIT__USE_STRMAP'
        __KHASH_IMPL(str, static kh_inline, const char *, void *, 1, kh_str_hash_func, kh_str_hash_equal)
        ^
../vendor/libgit2/src/khash.h:218:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h)                                            \
                   ^
````

https://gist.github.com/01e3c98204e251e8b2d9

**Comment by tbranyen** [comment]
@saper we're locked to a copy of openssl that builds just fine using the compilers on Travis-CI, for some reason node-gyp isn't cooperating with it (not sure why it's even affecting it).

**Comment by saper** [comment]
This particular problem is worked around by https://github.com/nodegit/nodegit/pull/707. It can be applied to master independently.

**Comment by tbranyen** [comment]
@saper thanks so much for looking into this, I just rebased your work and changed our test matrix to use Node 4.0 (removing iojs) fingers crossed.

**Comment by tbranyen** [comment]
Awesome, looking great on Linux and OS X now.  Back to the Windows drawing board :-p

**Comment by saper** [comment]
> Awesome, looking great on Linux and OS X now.  Back to the Windows drawing board :-p

I am still getting compilation errors, although unrelated to node 4.

**Comment by tbranyen** [comment]
@saper Ah I'm referring to the CI, we run Node 0.12 and Node 4.0 in Linux and OS X and both are passing ATM.

**Comment by saper** [comment]
On Mon, 14 Sep 2015, Tim Branyen wrote:

> @saper Ah I'm referring to the CI, we run Node 0.12 and Node 4.0 in Linux and OS X and both are passing ATM.

That does not mean things are good :)

Check out generated `src/checkout_options.cc` around line 536
with empty conditionals... fix in #708

**Comment by tbranyen** [comment]
but it gives me a green check mark :smile_cat:

**Comment by saper** [comment]
https://github.com/saper/nodegit/tree/mynode my attempts to improve the build (esp. with AppVeyor)

**Comment by saper** [comment]
So Windows failures are caused by the wrong path of the Win32 "delay hook". I have posted https://github.com/nodejs/node-gyp/issues/732 with description.

**Comment by saper** [comment]
After #717 got merged there, this PR causes `note.js` tests to fail:

````
1) Note "before each" hook for "can be created":
     Error: Reference 'refs/remotes/master/HEAD' not found
      at Error (native)
 
````

**Comment by tbranyen** [comment]
So ummm. do we merge this :-p

**Comment by tbranyen** [comment]
:boom: Thanks so much to @saper and @johnhaley81 for making this happen!

**Comment by johnhaley81** [comment]
:boom: :shipit:

**Comment by pandres95** [comment]
:tada:

**Comment by njj** [comment]
Does this mean we should be able to install using Node 4.0?

**Comment by tbranyen** [comment]
@njj yup, working great in my app running Node 4.0 right now

**Comment by njj** [comment]
@tbranyen Hmm okay, I'm getting an error w/ 4.1.0:

```
 define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nickjustice/Development/Mothership/node_modules/nodegit/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/nickjustice/Development/Mothership/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /Users/nickjustice/Development/Mothership/node_modules/nodegit
gyp ERR! node -v v4.1.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/nickjustice/Development/Mothership/node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined
``
Any ideas @tbranyen?

**Comment by tbranyen** [comment]
`rm -rf node_modules`
`node generate`
`npm install`

Ensure you're on Node 4.0.

**Comment by njj** [comment]
@tbranyen Hmm no such luck, whats `node generate`?  Is Node 4.1.0 the issue?

```
> node server.js

module.js:338
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nickjustice/Development/Mothership/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by tbranyen** [comment]
@njj We haven't published any new versions, so I'm assuming you're cloning our repository and running `npm install` there.  If not, try doing something like:

``` json
{
  "dependencies": { "nodegit": "nodegit/nodegit" }
}
```

In your package.json.

**Comment by ChristianMurphy** [comment]
@tbranyen tried that on both node 4.0 and 4.1
getting the warning
```
[nodegit] Configuring libssh2.
{ [Error: spawn /.../node_modules/nodegit/vendor/libssh2/configure ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /.../node_modules/nodegit/vendor/libssh2/configure',
  path: '/.../node_modules/nodegit/vendor/libssh2/configure',
  spawnargs: [],
  cmd: '/.../node_modules/nodegit/vendor/libssh2/configure' }
```

locally running nodegit@60e3f2aff7be57afb8d76d5e9adbf0b2459a6232
on ubuntu 15.04

**Comment by saper** [comment]
can you `git clean -dxf` and try again?

**Comment by ChristianMurphy** [comment]
I ran
```
git clean -dxf
npm install
```

on node 4.0 and got same error, checking on 4.1 now

**Comment by njj** [comment]
Everything works for me by cloning this repo into my `node_modules` and manually running `npm install` inside the repo.

**Comment by saper** [comment]
On Thu, 17 Sep 2015, Nick wrote:

> Everything works for me by cloning this repo into my `node_modules` and manually running `npm install` inside the repo.

That's because node 4.0 version is not yet released.

**Comment by ChristianMurphy** [comment]
@saper @tbranyen 
Okay when I clone nodegit using git and build, it builds correctly.
If I download latest using NPM from `"nodegit/nodegit"` and it tries to build from there, the build fails with the libssh2 error.

**Comment by tbranyen** [comment]
I'm not sure why that would be, maybe try specifying the latest SHA.

**Comment by ChristianMurphy** [comment]
I tried `"nodegit/nodegit#60e3f2aff7be57afb8d76d5e9adbf0b2459a6232"` as well same result

**Comment by maxkorp** [comment]
Ooh, do you have openssl-dev or whatever it's called installed?

**Comment by saper** [comment]
> I tried `"nodegit/nodegit#60e3f2aff7be57afb8d76d5e9adbf0b2459a6232"` as well same result

git fetching is very tricky to get right. I think npm gave up in fixing this.

**Comment by maxkorp** [comment]
@saper Really? I've used that to great success. That's unfortunate if so. 

I know they have a lot of issues with build lifecycle with nodegit manually works around currently though, and that seems to just go in a loop of "so why do we need this". Don't think they gave up on that at least.

**Comment by saper** [comment]
> @saper Really? I've used that to great success. That's unfortunate if so. 

Check out jokes in the npm's CHANGELOG.md :) But seriously plain
clone over git should work. I've got bitten by trying to use
git URLs in the package.json for dependencies.

> I know they have a lot of issues with build lifecycle with nodegit
> manually works around currently though, and that seems to just go in a
> loop of "so why do we need this". Don't think they gave up on that at
> least.

It is possible that it does not work since #715. I am still lost
in the maze of our lifecycle scripts.

**Comment by maxkorp** [comment]
Yeah I've been shaving those down bit by bit as I get the chance. If I could find a good gypfile for libssh2, we could remove them almost entirely.

**Comment by saper** [comment]
> Yeah I've been shaving those down bit by bit as I get the chance. If
> I could find a good gypfile for libssh2, we could remove them almost
> entirely.

You man to get rid of autoconf? Will be difficult, because gyp
is not meant to replace it :(

**Comment by maxkorp** [comment]
Yeah, I know. Very unfortunate, really :/ 
I've found one or two that seem to work cross platform for smaller applications, but no idea how tested they are etc. We can't get rid of the lifecyclescirpts without getting rid of the autoconf, though.

**Comment by ChristianMurphy** [comment]
@maxkorp 
>  you have openssl-dev or whatever it's called installed?

I have `openssl`, `libssl-dev` and `libssh-dev` installed my system.

**Comment by ChristianMurphy** [comment]
> git fetching is very tricky to get right. I think npm gave up in fixing this.

@saper 

I checked my file system and it appears that NPM did fetch the correct version of the code down.

I'm wondering if possibly pulling the code from Git using NPM might trigger the `.npmignore` instead of the `.gitignore` and leave out a file needed to build.

**Comment by maxkorp** [comment]
It will respect both the .gitignore AND the .npmignore, ignoring anything specified by either (but explicit includes from one, will not override excludes by the other). That said, that was never a problem before.
#715 may be related however.

**Comment by saper** [comment]
> It will respect both the .gitignore AND the .npmignore, ignoring anything specified by either (but explicit includes from one, will not override excludes by the other). That said, that was never a problem before.
> #715 may be related however. 

"npm install" called from the lifecycle script fails in so many beautiful ways... so I'd rather not do it again.

**Comment by maxkorp** [comment]
Oh totally. Not a fan either. Do note however that it was `npm install --ignore-scripts` which prevents anything from calling lifecyclescripts (blocking an infinite recursion)`. We can dig into this in the other issue if needed though. (if we can confirm that it is an issue)

**Comment by saper** [comment]
@ChristianMurphy can you try #726 

    npm install 'git://github.com/saper/nodegit#configurestays

It lets me to go past the configure side.

We the hell our beautiful code full of promises is unable to produce an error message
that `configure` is missing:

````
[nodegit] Configuring libssh2.
npm WARN unmet dependency /home/saper/node_modules/node-sass requires nan@'^2.0.8' but will load
npm WARN unmet dependency /home/saper/node_modules/nan,
npm WARN unmet dependency which is version 2.0.5
npm WARN unmet dependency /home/saper/node_modules/node-sass requires request@'^2.61.0' but will load
npm WARN unmet dependency /home/saper/node_modules/request,
npm WARN unmet dependency which is version 2.55.1
nodegit@0.4.1 nodegit
├── promisify-node@0.2.1
├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@3.0.2 (asap@2.0.3)
├── fs-extra@0.18.4 (jsonfile@2.2.2, graceful-fs@3.0.8, rimraf@2.4.3)
├── node-pre-gyp@0.6.10
└── npm@2.14.3
````

Not to mention it would be nice to return an error code so that `npm` stops. Also #713.

**Comment by ChristianMurphy** [comment]
@saper installing from `git://github.com/saper/nodegit#configurestays` succeeded :tada:

**Comment by saper** [comment]
> @saper installing from `git://github.com/saper/nodegit#configurestays` succeeded :tada: 

I have merged the change, so now plain `git://github.com/nodegit/nodegit` should work.

**Comment by ssreekanth** [comment]
@saper Is the nodegit build working on windows now?

I tried installing from 
```
nodegit/nodegit#330abdb21dc3619c495bb4e975563fab1561659d
```
but still failing on windows -
```
npm ERR! nodegit@0.4.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
```
However, on Linux/OSX, it works fine.

**Comment by saper** [comment]
@ssreekanth This is means that the compilation failed. Do you get anything more than that? Error messages from the compiler?

**Comment by ssreekanth** [comment]
@saper These are the error messages I got -

```
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "SET HOME=%HOME%\.atom-shell-gyp&&  C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit\node_modules\.bin\node-gyp rebuild --target=0.33.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ssettipalli\\_personal_work\\sandbox\\nodegit-test\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.33.0" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "SET HOME=%HOME%\\.atom-shell-gyp&&  C:\\Users\\ssettipalli\\_personal_work\\sandbox\\nodegit-test\\node_modules\\nodegit\\node_modules\\.bin\\node-gyp rebuild --target=0.33.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"' }
undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.4.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the nodegit@0.4.1 install script 'node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\npm-debug.log
```
And my package.json is 

```json
{
  "name": "Sample",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "atom-shell": "0.33.0",
    "electron": "0.33.0"
  },
  "dependencies": {
    "nodegit": "nodegit/nodegit#330abdb21dc3619c495bb4e975563fab1561659d"
  },
  "devDependencies": {
    "electron-prebuilt": "0.33.0",
    "electron-rebuild": "^1.0.0"
  }
}
```

**Comment by saper** [comment]
@ssreekanth Can you check if https://github.com/nodegit/nodegit/pull/729 fixes the issue.

**Comment by ssreekanth** [comment]
@saper it is still failing..

```
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit\node_modules\.bin\node-gyp rebuild --target=0.33.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ssettipalli\\_personal_work\\sandbox\\nodegit-test\\node_modules\\nodegit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.33.0" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd C:\Users\ssettipalli\_personal_work\sandbox\nodegit-test\node_modules\nodegit
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "C:\\Users\\ssettipalli\\_personal_work\\sandbox\\nodegit-test\\node_modules\\nodegit\\node_modules\\.bin\\node-gyp rebuild --target=0.33.0  --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"' }
undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodegit"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.4.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
```

**Comment by deyhle** [comment]
When will this be released to npm?

**Comment by johnhaley81** [comment]
@deyhle it's out now as 0.5.0

**Pull request merged**
