### PR TITLE
TravisCI manifest cleanup

### PR DESCRIPTION
**Pull request by Turbo87**
This PR cleans up the TravisCI manifest file. e.g. installing `nvm` on Linux is unnecessary because it's preinstalled, lcov should only be installed if it is actually needed, ...

### CODE REVIEW

**Comment by tbranyen** [comment]
Awesome! Thank you :+1:

**Comment by Turbo87** [comment]
@tbranyen maybe I'm missing something, but where did those changes go? I can't find them in https://github.com/nodegit/nodegit/blob/master/.travis.yml anymore?!

**Comment by johnhaley81** [comment]
Argh, that was my fault. I'll fix it up...

**Comment by johnhaley81** [comment]
Everything should be ok now. Sorry about that =/

**Pull request merged**
