### PR TITLE
Fixes segfault issue recorded in #406

### PR DESCRIPTION
**Pull request by tbranyen**
A segfault was occuring when passing null values to `NanNew`, this patch
will the bug for `const char *` and `unsigned int` C types.  We'll
definitely need to add more in the future.

### CODE REVIEW

**Comment by tbranyen** [comment]
@Lange if you could give this a branch a shot, I believe it'll address your issue.

**Comment by Lange** [comment]
Tested, no segfault! :clap: :beers:

**Comment by johnhaley81** [comment]
:+1: nice going tbranyen

**Comment by johnhaley81** [comment]
I think the appveyor breaking is unrelated to this PR. I'm going to merge this in and look into fixing the breaking CI in a different PR. Don't want it holding up all of these PR's (#416 and #422).

**Pull request merged**
