### PR TITLE
[WIP] Added in some diff functions from libgit2

### PR DESCRIPTION
**Pull request by johnhaley81**
New functions:
git_diff_tree_to_workdir
git_diff_tree_to_workdir_with_index

### CODE REVIEW

**Comment by kmctown** [comment]
`Diff.treeToWorkdirWithIndex` is finding staged changes, but the line content is incorrect. Have not yet been able to figure out the source of the issue.

**Comment by kmctown** [comment]
Definitely can do that, I actually think it's not even necessary to `git add` if the right options are passed into the workdir diff function. Currently wandering libgit2 trying to figure out where this broke.

**Comment by kmctown** [comment]
@johnhaley81 rebased `0.2.5` code from master and it looks ready to go

**Comment by tbranyen** [comment]
Looks good to merge! @kmctown feel free to merge.

**Comment by maxkorp** [comment]
:+1:

**Comment by johnhaley81** [comment]
Thanks for the PR @kmctown!

**Comment by kmctown** [comment]
Np! :+1:

**Pull request merged**
