### PR TITLE
Upgrade to nan 1.7.0

### PR DESCRIPTION
**Pull request by orderedlist**
Hopefully this'll fix the apm install issues.

### CODE REVIEW

**Comment by johnhaley81** [comment]
We'll need to add atom shell and nwjs into our test matrix.

**Comment by orderedlist** [comment]
Yeah, I still can't get `apm install` to work pointing to this sha. :cry:

**Comment by orderedlist** [comment]
`apm install` worked with that last commit.

**Comment by orderedlist** [comment]
yes

**Comment by johnhaley81** [comment]
:+1:

**Pull request merged**
