### PR TITLE
Test in Node 0.12 and io.js

### PR DESCRIPTION
**Pull request by tbranyen**

### CODE REVIEW

**Comment by johnhaley81** [comment]
:+1:

**Comment by johnhaley81** [comment]
https://travis-ci.org/nodegit/nodegit/jobs/53249611#L528

I'm going to cancel and restart this in Travis

**Comment by johnhaley81** [comment]
Interesting... it didn't queue up on Travis.

**Comment by maxkorp** [comment]
Right? o.O

**Comment by maxkorp** [comment]
W/e, just reset to the prior commit and recommitted the same changes.

**Comment by johnhaley81** [comment]
I'm switching us over to use rvagg/pangyp until TooTallNate/node-gyp is updated.

Reference: https://github.com/iojs/io.js/issues/433

**Comment by johnhaley81** [comment]
We might want to bump up timeouts on our CI tests since Travis has been running slow lately.

**Comment by johnhaley81** [comment]
Pretty sure [this](https://code.google.com/p/chromium/issues/detail?id=459797) was the issue.

**Comment by johnhaley81** [comment]
Getting `module did not self register`

**Comment by johnhaley81** [comment]
pangyp currently doesn't work in windows :(

https://github.com/rvagg/pangyp/issues/4

**Comment by johnhaley81** [comment]
Should we just keep going on with the caveat of "Does not work in iojs for windows right now"?

**Comment by tbranyen** [comment]
Yup, works well for me!

**Pull request merged**
