### PR TITLE
Bump libgit2 to 43275f512ef888a14c43bde8007251ce595be32a + unmerged proxy fixes

### PR DESCRIPTION
**Pull request by srajko**

### CODE REVIEW

**Comment by rcjsuen** [comment]
Bumping libgit2 to master would also fix #1220. Keep in mind though that things are a little fishy there since the test suite crashes but the builds are green...

**Comment by srajko** [comment]
@rcjsuen in which builds are you seeing the tests crash?

**Comment by rcjsuen** [comment]
@srjako Take a look at the AppVeyor and Travis CI builds that got spawned off for #1220. While AppVeyor is correctly red, Travis CI is green even though the test suite has segfaulted... :(

**Comment by srajko** [comment]
That is indeed fishy :-)  Thanks for pointing that out, definitely something we should resolve.

**Comment by tommoor** [comment]
0.17.0 is also crashing our test suites, I'm not sure why as karma disconnects with no result - subscribing to this in the hope that this will fix!

**Comment by johnhaley81** [comment]
@srajko this needs a rebase now :(

**Comment by johnhaley81** [comment]
Well, everything is green except for the 32-bit linux builds which aren't really related to this PR and are fixed in #1241 so I'll admin merge this. Thanks @srajko

**Comment by johnhaley81** [comment]
This includes libgit2 PRs:

- [Use a shared buffer in calls of git_treebuilder_write to avoid heap contention #3892](https://github.com/libgit2/libgit2/pull/3892)
- [WinHTTP: set proper error messages when SSL fails #4050](https://github.com/libgit2/libgit2/pull/4050)
- [Clang analyzer run #4051](https://github.com/libgit2/libgit2/pull/4051)
- [Extend packfile in increments of page_size. #4053](https://github.com/libgit2/libgit2/pull/4053)
- [Fix general example memory leaks #4078](https://github.com/libgit2/libgit2/pull/4078)
- [WIP: some coverity & compiler warning fixes #4086](https://github.com/libgit2/libgit2/pull/4086)
- [Fix a few recent warnings #4087](https://github.com/libgit2/libgit2/pull/4087)
- [Fix uninitialized variable warning #4095](https://github.com/libgit2/libgit2/pull/4095)
- [Update docs for git_oid_fromstrn and p #4096](https://github.com/libgit2/libgit2/pull/4096)
- [Fix digest credentials for proxy in windows #4104](https://github.com/libgit2/libgit2/pull/4104)
- [Vector reverse overflow #4105](https://github.com/libgit2/libgit2/pull/4105)
- [Flag given_opts in git_revert as optional #4108](https://github.com/libgit2/libgit2/pull/4108)
- [Flag checkout_opts in git_reset as optional #4109](https://github.com/libgit2/libgit2/pull/4109)
- [dirname with DOS prefixes #4111](https://github.com/libgit2/libgit2/pull/4111)
- [Add support for lowercase proxy environment variables #4112](https://github.com/libgit2/libgit2/pull/4112)
- [Flag options in git_stash_apply and git_stash_pop as being optional #4117](https://github.com/libgit2/libgit2/pull/4117)
- [rename detection: don't try to detect submodule renames #4119](https://github.com/libgit2/libgit2/pull/4119)
- [tests: fix permissions on testrepo.git index file #4121](https://github.com/libgit2/libgit2/pull/4121)

It also includes the 2 non-merged libgit2 PRs:

 - [negotiate always fails via libcurl #4126](https://github.com/libgit2/libgit2/pull/4126)
 - [Fix proxy auto detect not utilizing callbacks #4097](https://github.com/libgit2/libgit2/pull/4097)

Both of which are proxy related.

**Pull request merged**
