### PR TITLE
Tree Entry getBlob() should also support the callback pattern.

### PR DESCRIPTION
**Pull request by jeffwilcox**
Hi,
As this is my first contribution to this project, let me know what I can change, i.e. should I merge to a new branch name or is a direct-to-master preferred. (Contributing.MD didn't have a ton of info on the logistics of moving changes around)

## Change Background

While moving code from the older v0.1.x codebase to the latest, I tried making minimal changes and renames in some functions. A majority of my Node code at this time is not using promises. While calling `getBlob(callback)` on a tree_entry, nothing happened.

I simply mimicked the format used for `getTree` in tree_entry to be consistent (although I'm not setting the `entry` instance on a property like the tree function does).

## Tests

All `mocha` tests passing related to this change. However...

- Clone."can clone with ssh" is a failing test, both before and after the change, on Windows 8.1 x64 with Node v0.12.0.

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Oh the irony, a `404` issue ID...

**Comment by tbranyen** [comment]
Looks good to me, what do you mean typo @johnhaley81 ?

**Comment by johnhaley81** [comment]
@jeffwilcox fyi that test will fail unless you're running an ssh agent and git's configured to use it.

**Comment by jeffwilcox** [comment]
I found the typo... a missing space in a test name. Fixing!

**Comment by jeffwilcox** [comment]
Closing pull for now, will squash and create a new pr.

**Pull request closed without merging**
