### PR TITLE
Bump nan

### PR DESCRIPTION
**Pull request by johnhaley81**

### CODE REVIEW

**Comment by johnhaley81** [comment]
This should give us compatibility with io.js 2

**Comment by johnhaley81** [comment]
This is needed because of https://github.com/nodejs/io.js/issues/1620

**Comment by tbranyen** [comment]
Awesome! Testing locally.

**Comment by tbranyen** [comment]
:+1:

**Comment by maxkorp** [comment]
The screams of relief when the http-parser update fixed the segfaults...

**Pull request merged**
