### PR TITLE
[WIP] Push example

### PR DESCRIPTION
**Pull request by johnhaley81**

### CODE REVIEW

**Comment by Snugug** [comment]
Did this land? I'm on 0.5.0 and when I try and follow the example, I get `Git.Push.create is not a function`

**Comment by Snugug** [comment]
(sorry for resurrecting and old issue)

**Comment by johnhaley81** [comment]
This is an old example. Check the latest on master https://github.com/nodegit/nodegit/blob/master/examples/push.js

**Comment by Snugug** [comment]
Thank you!

**Pull request merged**
