### PR TITLE
Update to 0.4.0

### PR DESCRIPTION
**Pull request by tbranyen**
Updated all third-party dependencies as well.

### CODE REVIEW

**Comment by tbranyen** [comment]
Boom! I'm ready to publish 0.4.0, when ya'll are.

**Comment by johnhaley81** [comment]
Do we want to get https://github.com/nodegit/nodegit/tree/blobToBuffer in?

**Comment by tbranyen** [comment]
That'd be cool, I'm not in any particular rush, especially since the next steps are publishing...

**Comment by johnhaley81** [comment]
All that needs now is a solid test. But it's working.

**Comment by bleathem** [comment]
What's the status of this 0.4.0 release?

**Comment by tbranyen** [comment]
@bleathem will probably happen tomorrow *hopefully*

**Comment by bleathem** [comment]
:+1: you guys rock!

**Comment by tbranyen** [comment]
For some reason Linux w/ Node 0.12 is the only one failing.  No idea why, but we need this figured out before publishing.

**Comment by tbranyen** [comment]
@johnhaley81 nan isn't the issue as far as I can tell.  I noticed the same errors with or without it.  As you can see by the previous builds, the latest version of nan works just fine in everything except for Node 0.12 in Linux.

**Comment by johnhaley81** [comment]
Nan 1.8.x  was doing some weird stuff with electron for sure but it does seem to fix it for CI. Something weird is going on. I did remember people on the nan repo saying that 1.8 is not backwards compatible. Are you able to build it locally with 1.8?

**Comment by tbranyen** [comment]
No I wasn't able to build with 1.7 or 1.8.  Although like you said CI appears to be fixed.

**Comment by tbranyen** [comment]
I'll update the changelog again in a commit straight to master so that it gets updated to v0.4.0

**Pull request merged**
