### PR TITLE
[WIP] Additional Log Output During Build

### PR DESCRIPTION
**Pull request by samkelleher**
(maybe I can separate out the node 5 on travis build).

Essentially I've been trying to resolve build issues. The existing build script wasn't handling failure and would just skip ahead regardless of error, or end without writing - this PR is simply adding console logging at each build step, and forcing a failure on errors.

### CODE REVIEW

**Comment by maxkorp** [comment]
@samkelleher seems like a few things in here are already in via PR. Can I get you to split this into smaller PRs please?

**Comment by samkelleher** [comment]
Yeh the node 5 I added separately as I'm still having issues producing a binary output. I'll tidy this up tomorrow. This pr will simply add more verbose logging during install.

**Comment by johnhaley81** [comment]
@samkelleher @maxkorp is this still needed?

**Comment by johnhaley81** [comment]
:+1:

**Pull request closed without merging**
