### PR TITLE
Removes Node 0.11 testing completely

### PR DESCRIPTION
**Pull request by tbranyen**
Doesn't make sense to just remove on Windows.  Lets just drop 0.11 completely for now.

### CODE REVIEW

**Comment by johnhaley81** [comment]
:+1:

We should look into getting io.js testing into CI.

**Comment by johnhaley81** [comment]
Should we wait on merging this until we have io.js testing in CI?

**Comment by maxkorp** [comment]
Eh, I don't think so. The two are pretty radically different in regards to environment, so until that normalizes i'd just as soon not loop it into CI at all.

**Comment by tbranyen** [comment]
Yeah, we can add in test matrices in the future.  I just don't want to support something that Joyent isn't supporting.

**Pull request merged**
