### PR TITLE
Add automatically generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.
I created a [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator), that generate change log file based on tags, issues and merged pull requests (and split them to separate lists according labels) from GitHub issue tracker.
[This Change Log](https://github.com/skywinder/nodegit/blob/add-change-log-file/CHANGELOG.md) was automatically generated by this script.
It helps to easily found what and when was fixed and implemented.
You can easily update this file in future by running script: `github_changelog_generator` in your repo folder.
Hope you find this commit as useful.

### CODE REVIEW

**Comment by johnhaley81** [comment]
Any objections to this @nodegit/owners?

**Comment by maxkorp** [comment]
Hrm, I like that a lot for incrementals, not sure on the big update like this one. many of those PRs are fixing things introduced in the release, so it seems odd to include them in the changelog. At minimum, that is an awesome starting point, and potentially an all around solution in many cases (dot releases etc). Awesome awesome tool.

The only other thought is that currently we have history.md, this should be prepended there, either instead of included here, or in addition to (I'm not opposed to having a changelog for the latest version separate from the history).

**Comment by skywinder** [comment]
@maxkorp thanks for mention it. 
It will be a nice feature: to not include PR's, that fix closes another issues. I will research, how to implement it.

About excluding issues: this script can exclude/include issues by specific labels.

**Comment by maxkorp** [comment]
Interesting! That would be great, since we could exclude issues fixed that were introduced in the same release

**Comment by skywinder** [comment]
@maxkorp so, what your opinion: is it better to exclude PR's or issues, that closed by PR from change log?

**Comment by tbranyen** [comment]
@skywinder can you also add a useful hash name to the header anchors?  Something like

``` html
<a name="v0-0-6" href="some_gh_changelog">v0.0.6</a>
```

**Comment by skywinder** [comment]
@tbranyen What do you mean? What should be in place of "some_gh_changelog"?
Now every tag name - is a link to this tag in project: 
For example tag  0.2.4 links to  https://github.com/nodegit/nodegit/tree/v0.2.4

**Comment by tbranyen** [comment]
We've brought this into our site, should we maintain a file in this repo as well?

**Comment by skywinder** [comment]
@tbranyen 
If you want to refer to specific tag in changelog (e.g. Add Anchor Tags To Jump To Specific Location On A Changelog), you can click on the chain image close with tag name:
screen shot 2015-03-17 at 13 17 19

And the browser will redirect you to the link with this tag as anchor:
( https://github.com/skywinder/nodegit/blob/add-change-log-file/CHANGELOG.md#v026-2015-01-20 in that case)
Is it a option, that you are looking for?

**Comment by maxkorp** [comment]
I think it's sort of customary to include the changelog with the source, yeah. We already have HISTORY.md but we can rename it and append it to this.

**Comment by skywinder** [comment]
But now your history has only one tag.
I decide to take this name, because it's kind of standart.  ( keepachangelog.com )

But you can specify your custom name for output file:

    github_changelog_generator -o HISTORY.md

**Comment by maxkorp** [comment]
Yeah, I was saying keep this, and append the contents of history to this ;)

**Comment by johnhaley81** [comment]
:+1:

**Comment by johnhaley81** [comment]
@nodegit/owners how do you guys feel about merging this?

**Comment by tbranyen** [comment]
Yeah might as well.  We can always change it later.  Something is better than nothing.

**Comment by skywinder** [comment]
Hooray, guys! :+1: 
BDW, I will add one feature soon: https://github.com/skywinder/github-changelog-generator/issues/54 
Since you are use quite different labels, rather than default github labels (`Bug` - `bug`, `Modification`- `enhancement `, `Question` - `question`) - this feature will help to make change log even more organised! I'll let you know when I'm done with it!

**Pull request merged**
